# Generated by Django 5.2 on 2025-04-21 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_remove_cartsitem_phone_and_more'),
        ('products', '0003_product_remove_phone_brand_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.DeleteModel(
            name='CartsItem',
        ),
    ]
